### ISSUE TITLE
extraneous dot before git repo name extension 

### ISSUE THREAD

**Issue by spyluxos** [PacktPublishing/Time-Series-Analysis-with-Python-Cookbook#1]
https://github.com/PacktPublishing/Time-Series-Analysis-with-Python-Cookbook..git
provokes error when you 'git clone' the repo.
Can you please rename to
https://github.com/PacktPublishing/Time-Series-Analysis-with-Python-Cookbook.git

**Comment by pnijhara** [comment]
@spyluxos, even if you put 100s of the dot before `.git`, it should still perform git clone without any error. Can you share your error logs, please?

**Comment by tatwan** [comment]
Hello @spyluxos hopefully you should not have an issue cloning the repo. If you use `https://github.com/PacktPublishing/Time-Series-Analysis-with-Python-Cookbook..git` it should work without a problem. The only issues may occur if you are trying to share the GitHub URL on social media or email for example, in many cases, these platforms will omit the dot from `https://github.com/PacktPublishing/Time-Series-Analysis-with-Python-Cookbook.` and the URL will not work (it will show a 404 error page). I am working with the Repo admins to resolve this issue.
