### ISSUE TITLE
Can I use sklearn instead of sktime?

### ISSUE THREAD

**Issue by rlacjfjin** [PacktPublishing/Time-Series-Analysis-with-Python-Cookbook#2]
As chap.12 using machine learning package to predict time series, I see the book use non-linear models with sktime. But I think sklearn is also provide such regression models, although you say sklearn is general ML library.
Why I want to use sklearn is:

     sktime need numpy version: <1.23, but when I using pytorch the numpy need to 1.23 version, so in my project I need to switch version. But I use sklearn in linear model there not have such problems, and I want to extend non-linear models.
 
And is there any general function to training machine learning models such as train Neural Networks model in chap.13? Including tuning parametters.

Thanks,
Zhe.

**Comment by tatwan** [comment]
What a great question. Let me add a few pointers and hope this helps:

- In Chapter 1, the intent is to introduce the reader to managing different virtual environments, ideally to avoid conflicts with different package versions; you can create a different VM using conda or venv. I provided an export (example requirements.txt file for each chapter). This way, you do not have to worry about conflicts between versions ..etc. I do encourage readers not to skip that chapter. I just added a Jupyter notebook for Ch1 with a summary of these code snippets for reference.
- The main idea in Chapter 12 is learning how to prepare your Time Series for ML. Once that is done, as you said, you can use Scikit-Learn (sklearn) and pretty much any regressor (Linear Regression, KNN regressor, Random Forest Regressor ..etc.). The use of these non-linear models in the sktime recipe was not exclusive to sktime but a way to introduce sktime and, more specifically, the` make_reduction` function and the `TransformedTargetForecasterand` class. You will notice in that recipe we still imported these algorithms from sklearn library. 
- So, short answer, in the recipe "_One-step forecasting using linear regression models with scikit-learn_" you can use different regressors from sklearn without needing sktime. This is also stated in the "How it works" section as well as the "See Also" section.
- sktime has many nice features. It is mostly a wrapper on top of many popular Python libraries, including sklearn. I wanted to show that when using sktime, you can pass many time series type of data transformations within the transformation pipeline, and it will do it for you. But in the first recipe, "Preparing time series data for supervised learning," you also learned how to do such transformation on your own (using that example). 
- I will try and update the GitHub Notebook to show additional examples to make this clearer as well.

**Comment by rlacjfjin** [comment]
thank you for your reply.

As you said, I can indeed add the model I want in the regressors, this is where I overlooked, 
thanks!
