### ISSUE TITLE
Can´t clone the repo with lfs

### ISSUE THREAD

**Issue by marcelotorrescisterna** [PacktPublishing/Time-Series-Analysis-with-Python-Cookbook#3]
Hello! I just bought the book and I´m having issues cloning the repo. I installed lfs, however it keeps saying that objects don´t exist on the server
![clonerror](https://user-images.githubusercontent.com/69370786/184569027-8e43af4d-9998-4227-8c0f-b8d98400f830.jpg)
i

**Comment by tatwan** [comment]
Hi @marcelotorrescisterna ,

Thank you for buying the book and we are excited for you and hope you will enjoy it. Can you please try this snippet (notice the two dots). If this works, I will explain the issue.

`git clone https://github.com/PacktPublishing/Time-Series-Analysis-with-Python-Cookbook..git`

**Comment by marcelotorrescisterna** [comment]
Hi @tatwan I´m still having issues. This is the error:
![gitclone](https://user-images.githubusercontent.com/69370786/184659740-476b413c-9de4-487d-a475-b91166f2e030.jpg)

**Comment by tatwan** [comment]
Hi @marcelotorrescisterna I am able to confirm the issue. On MacOS/Linux terminal using the extra dot '.' does not pose an issue, but replicating using Git Bash on Windows I get the same issue. So, we are working on fixing this. We plan to rename the repo and remove the extra '.', and GitHub will handle all redirects to the new name this way other readers do not get impacted or confused.

Thank you very much for pointing this out. That extra "." should not have been there and we will get this resolved ASAP. I will update you once this is completed.

Moving forward there should be ONE repo once the fix is implemented.

**Comment by marcelotorrescisterna** [comment]
Thanks @tatwan looking forward!

Best regards

**Comment by tatwan** [comment]
Just to share an update, after identifying the issues I am still working with the team to get this resolved. We have identified the solution, this should be implemented in the next few days.

**Comment by marcelotorrescisterna** [comment]
Thanks @tatwan , I have another computer in which I work with Ubuntu, in that computer I was able to download the files.

Thanks!

**Comment by tatwan** [comment]
Quick update @marcelotorrescisterna we are still working on resolving this and renaming the repo, all redirects will be managed automatically other users do not need to make changes.

For your issue, please use this command
` git clone https://github.com/PacktPublishing/Time-Series-Analysis-with-Python-Cookbook..git .`

Add the `.` after the git and it will work on Git Bash. I tested it on Windows Git Bash and it worked without a problem. 

Here are the steps:

1. use mkdir to create a directory, you can call it as you like or similar name
2. CD into the directory
3. use the git clone git clone https://github.com/PacktPublishing/Time-Series-Analysis-with-Python-Cookbook..git . 
4. The dot in the end will download the content into the current directory 

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/4407286/187833435-a057f6e3-5acd-4c8a-ac9d-129593ea0490.png">

**Comment by tatwan** [comment]
@marcelotorrescisterna the repo has been renamed and this should resolve the issue. It has been tested. Any old references to previous name should still work, the redirect is handled by GitHub. 

Please let me know if you are facing any issues. I will mark this as closed.
