### ISSUE TITLE
Chapter 5, page 127 amzn_df_2020.to_sql() throws an error

### ISSUE THREAD

**Issue by HansHeytens** [PacktPublishing/Time-Series-Analysis-with-Python-Cookbook#4]
Hello,

running the to_sql() function throws an error:

OperationalError: (psycopg2.OperationalError) connection to server at "localhost" (::1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused (0x0000274D/10061)
	Is the server running on that host and accepting TCP/IP connections?

(Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by tatwan** [comment]
Hi @HansHeytens can you give more insights into your current setup to see if the issue can be reproduced. Originally, this was tested on a local environment running in a Docker container in which the port 5432 is exposed. Can you share your setup, maybe the version of the libraries you are using?
